### ISSUE TITLE
Can only download from the No-Intro directory

### ISSUE THREAD

**Issue by JakeyE17** [gearsandpens/MRScraper#1]
The System selection box only lists the systems under the No-Intro directory, is is intended or do you plan to add the other directories/systems too (such as Redump/Internet Archive etc)? 

Is it also possible to add an option to download all regions of a system at once?

**Comment by gearsandpens** [comment]
Yeah, I'm planning to add an 'Advanced mode' in version 1.1 that enables downloading from whatever directory you want. It's sort of a difficult conundrum as i want MRScraper to be as easy to use as possible. 

I've already implemented the 'disable region limits' checkbox in the main branch if you wanna take a look. Keep in mind though that I haven't completely tested everything so you might want to wait for 1.1 to release

**Comment by gearsandpens** [comment]
Released v1.1 with these improvements included

**Comment by Josef733** [comment]
> Yeah, I'm planning to add an 'Advanced mode' in version 1.1 that enables downloading from whatever directory you want. It's sort of a difficult conundrum as i want MRScraper to be as easy to use as possible.
> 
> I've already implemented the 'disable region limits' checkbox in the main branch if you wanna take a look. Keep in mind though that I haven't completely tested everything so you might want to wait for 1.1 to release

I realise this is a bit late, but there was an issue with unchecking the region limits that I managed to fix.
